eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
server:
  port: 8760
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
